
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
#      - 连接数据库
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/shop"
#        数据表
        tables: "user,item,item_cat,item_param,order"
#        增加desription的标签
        descriptionTag: true
#        关闭数据模型结构体属性的注释自动生成
        noModelComment: true