// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// ItemParam is the golang structure of table item_param for DAO operations like Where/Data.
type ItemParam struct {
	g.Meta    `orm:"table:item_param, do:true"`
	Id        interface{} //
	ItemCatId interface{} // 商品类目
	ParamData interface{} // 商品json参数
	CreateAt  *gtime.Time // 创建时间
	UpdateAt  *gtime.Time // 更新时间
}
