// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// Item is the golang structure of table item for DAO operations like Where/Data.
type Item struct {
	g.Meta    `orm:"table:item, do:true"`
	Id        interface{} // 商品id,商品编号
	Title     interface{} // 商品标题
	SellPoint interface{} // 商品卖点
	Price     interface{} // 商品价格单位元
	Num       interface{} // 库存数量
	Barcode   interface{} // 商品条形码
	Image     interface{} // 商品图片
	Cid       interface{} // 商品类目
	Status    interface{} // 商品状态 1-正常销售，2-停售
	CreateAt  *gtime.Time // 创建时间
	UpdateAt  *gtime.Time // 更新时间
}
