// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-shop/internal/dao/internal"
)

// internalItemCatDao is internal type for wrapping internal DAO implements.
type internalItemCatDao = *internal.ItemCatDao

// itemCatDao is the user access object for table item_cat.
// You can define custom methods on it to extend its functionality as you wish.
type itemCatDao struct {
	internalItemCatDao
}

var (
	// ItemCat is globally public accessible object for table item_cat operations.
	ItemCat = itemCatDao{
		internal.NewItemCatDao(),
	}
)

// Fill with you ideas below.
