// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-shop/internal/dao/internal"
)

// internalItemDao is internal type for wrapping internal DAO implements.
type internalItemDao = *internal.ItemDao

// itemDao is the user access object for table item.
// You can define custom methods on it to extend its functionality as you wish.
type itemDao struct {
	internalItemDao
}

var (
	// Item is globally public accessible object for table item operations.
	Item = itemDao{
		internal.NewItemDao(),
	}
)

// Fill with you ideas below.
