// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gf-shop/internal/dao/internal"
)

// internalItemParamDao is internal type for wrapping internal DAO implements.
type internalItemParamDao = *internal.ItemParamDao

// itemParamDao is the user access object for table item_param.
// You can define custom methods on it to extend its functionality as you wish.
type itemParamDao struct {
	internalItemParamDao
}

var (
	// ItemParam is globally public accessible object for table item_param operations.
	ItemParam = itemParamDao{
		internal.NewItemParamDao(),
	}
)

// Fill with you ideas below.
