// ================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// You can delete these comments if you wish manually maintain this interface file.
// ================================================================================

package service

import (
	"context"
	"gf-shop/internal/model"
	"gf-shop/internal/model/entity"
)

type (
	IItem interface {
		Create(ctx context.Context, in model.ItemCreateInput) (err error)
		Delete(ctx context.Context, id int64) (err error)
		Get(ctx context.Context, id int64) (data *entity.Item, err error)
	}
)

var (
	localItem IItem
)

func Item() IItem {
	if localItem == nil {
		panic("implement not found for interface IItem, forgot register?")
	}
	return localItem
}

func RegisterItem(i IItem) {
	localItem = i
}
