// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ItemCat is the golang structure for table item_cat.
type ItemCat struct {
	Id        int64       `json:"id"        description:""`
	ParentId  int64       `json:"parentId"  description:"父类目id"`
	Name      string      `json:"name"      description:"类目名称"`
	Status    int         `json:"status"    description:"状态 1-正常销售，2-停售"`
	SortOrder int         `json:"sortOrder" description:"排序号"`
	IsParent  int         `json:"isParent"  description:"是否为父类目"`
	CreateAt  *gtime.Time `json:"createAt"  description:"创建时间"`
	UpdateAt  *gtime.Time `json:"updateAt"  description:"更新时间"`
}
