// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// ItemParam is the golang structure for table item_param.
type ItemParam struct {
	Id        int64       `json:"id"        description:""`
	ItemCatId int64       `json:"itemCatId" description:"商品类目"`
	ParamData string      `json:"paramData" description:"商品json参数"`
	CreateAt  *gtime.Time `json:"createAt"  description:"创建时间"`
	UpdateAt  *gtime.Time `json:"updateAt"  description:"更新时间"`
}
