// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// Order is the golang structure for table order.
type Order struct {
	Id          int64       `json:"id"          description:""`
	OrderNo     string      `json:"orderNo"     description:"订单号"`
	OrderUnique string      `json:"orderUnique" description:"流水号"`
	Money       int         `json:"money"       description:"金额"`
	Status      int         `json:"status"      description:"状态"`
	CreateAt    *gtime.Time `json:"createAt"    description:"创建时间"`
	UpdateAt    *gtime.Time `json:"updateAt"    description:"更新时间"`
}
